# Generated by Django 3.2.16 on 2023-05-25 03:05

from django.db import migrations, models
import django.db.models.deletion 


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('path', models.CharField(default='', max_length=255)),
                ('course_id', models.CharField(default='', max_length=255)),
                ('org_id', models.CharField(default='', max_length=255)),
                ('module', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('agent', models.CharField(default='', max_length=255)),
                ('host', models.CharField(default='', max_length=255)),
                ('accept_language', models.CharField(default='', max_length=255)),
                ('event', models.CharField(default='', max_length=255)),
                ('event_type', models.CharField(default='', max_length=255)),
                ('event_source', models.CharField(default='', max_length=255)),
                ('page', models.CharField(default='', max_length=255)),
                ('time', models.DateTimeField(blank=True, default=None, null=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='apiEol.context')),
            ],
        ),
    ]
