# Generated by Django 3.2.16 on 2023-05-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiEol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='referer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='session',
            field=models.CharField(default='', max_length=255),
        ),
    ]
