# Generated by Django 3.2.16 on 2023-05-25 03:10

import json, os
from django.db import migrations



def load_data(apps, schema_editor):
    print("Start Loading data")
    data_file_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'data.json')
    with open(data_file_path, 'r') as f:
        data = json.load(f)
    events = []
    print("Loaded data")
    return 
class Migration(migrations.Migration):

    dependencies = [
        ('apiEol', '0002_auto_20230524_2310'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
